/**
 * Manifest de tablas que deben tener RLS en migraciones DrFlow.
 * Actualizar al agregar tablas clínicas nuevas.
 */
export const TABLES_REQUIRING_RLS = [
  "clinics",
  "profiles",
  "clinic_members",
  "specialties",
  "locations",
  "professionals",
  "patients",
  "patient_clinical_profiles",
  "patient_attachments",
  "pami_vademecum",
  "availability_rules",
  "schedule_blocks",
  "consultation_reasons",
  "appointments",
  "clinical_records",
  "clinical_record_attachments",
  "clinical_record_audit",
  "clinical_templates",
  "prescription_drafts",
  "prescription_events",
  "prescription_templates",
  "coverage_rules",
  "reminder_logs",
  "telemedicine_sessions",
  "payments",
  "public_booking_links",
  "consent_records",
  "audit_logs",
  "clinic_plugins",
  "clinic_feature_flags",
  "clinic_jobs",
  "clinic_observability_events",
  "pathologies",
  "drugs",
  "pathology_drugs",
  "symptoms",
  "pathology_symptoms",
  "medical_orders",
  "clinic_invitations",
  "patient_app_share_log",
  "cash_charge_types",
  "cash_payment_methods",
  "cash_charges",
  "patient_ledger_entries",
  "cash_invoices",
  "cash_daily_closures",
  "patient_admin_documents",
  "user_ai_connections",
  "clinic_member_permissions",
  "clinic_shared_ai_connections",
  "pami_planilla_categories",
  "pami_planilla_templates",
  "pami_planilla_template_versions",
  "pami_planilla_template_fields",
  "pami_planilla_clinic_template_settings",
  "appointment_status_history",
  "waiting_list",
  "appointment_notification_queue",
] as const;

/** RPC SECURITY DEFINER que deben acotar tenant (nombre → migración de referencia). */
export const SECURITY_DEFINER_RPC_CHECKS: { name: string; migrationHint: string }[] = [
  { name: "setup_user_clinic", migrationHint: "024" },
  { name: "seed_pami_cabecera_for_clinic", migrationHint: "030" },
  { name: "submit_public_booking", migrationHint: "010" },
  { name: "get_public_booking_occupancy", migrationHint: "045" },
  { name: "clinic_subscription_active", migrationHint: "047" },
  { name: "can_write_clinical", migrationHint: "047" },
  { name: "get_patient_appointment_statuses", migrationHint: "022" },
  { name: "seed_demo_patients_for_clinic", migrationHint: "019" },
  { name: "claim_clinic_jobs", migrationHint: "051" },
  { name: "complete_clinic_job", migrationHint: "051" },
  { name: "purge_old_observability_events", migrationHint: "052" },
  { name: "accept_clinic_invitations_for_user", migrationHint: "018" },
  { name: "cancel_patient_appointment", migrationHint: "026" },
  { name: "record_patient_data_consent", migrationHint: "033" },
  { name: "record_informed_consent", migrationHint: "098" },
  { name: "remove_clinic_member_user", migrationHint: "035" },
  { name: "delete_own_account", migrationHint: "039" },
  { name: "update_my_doctor_profile", migrationHint: "025" },
  { name: "search_pami_vademecum", migrationHint: "042" },
  { name: "search_pathologies", migrationHint: "005" },
  { name: "search_symptoms", migrationHint: "011" },
  { name: "search_pathologies_by_symptoms", migrationHint: "011" },
];
