/**
 * Manifest de tablas que deben tener RLS en migraciones NexClinic.
 * Actualizar al agregar tablas clínicas nuevas.
 */
export const TABLES_REQUIRING_RLS = [
  "clinics",
  "profiles",
  "clinic_members",
  "specialties",
  "locations",
  "professionals",
  "patients",
  "patient_clinical_profiles",
  "patient_attachments",
  "patient_portal_sessions",
  "pami_vademecum",
  "national_medications",
  "availability_rules",
  "schedule_blocks",
  "consultation_reasons",
  "appointments",
  "clinical_records",
  "clinical_record_attachments",
  "clinical_record_audit",
  "clinical_templates",
  "prescription_drafts",
  "prescription_events",
  "prescription_templates",
  "coverage_rules",
  "reminder_logs",
  "telemedicine_sessions",
  "payments",
  "public_booking_links",
  "consent_records",
  "audit_logs",
  "clinic_plugins",
  "clinic_feature_flags",
  "clinic_jobs",
  "clinic_subscriptions",
  "clinic_subscription_payments",
  "clinic_observability_events",
  "pathologies",
  "drugs",
  "pathology_drugs",
  "clinical_diagnoses",
  "clinical_treatments",
  "clinical_record_diagnoses",
  "clinical_record_treatments",
  "patient_problem_list",
  "symptoms",
  "pathology_symptoms",
  "medical_orders",
  "clinic_invitations",
  "patient_app_share_log",
  "cash_charge_types",
  "cash_payment_methods",
  "cash_charges",
  "patient_ledger_entries",
  "cash_invoices",
  "cash_daily_closures",
  "patient_admin_documents",
  "user_ai_connections",
  "clinic_member_permissions",
  "clinic_shared_ai_connections",
  "pami_planilla_categories",
  "pami_planilla_templates",
  "pami_planilla_template_versions",
  "pami_planilla_template_fields",
  "pami_planilla_clinic_template_settings",
  "appointment_status_history",
  "waiting_list",
  "user_device_sessions",
  "appointment_notification_queue",
  "clinical_favorites",
  "clinical_recent_usage",
  "plans",
  "features",
  "plan_features",
  "clinic_entitlement_subscriptions",
  "clinic_feature_overrides",
  "feature_usage",
  // Phase 10 — tables with RLS that were missing from CI manifest (103–129)
  "clinic_api_keys",
  "os_fee_schedules",
  "os_billable_items",
  "os_liquidation_batches",
  "data_import_sessions",
  "import_mapping_templates",
  "clinic_plan_recommendations",
  "commercial_usage_thresholds",
  "privacy_rights_requests",
] as const;

/** RPC SECURITY DEFINER que deben acotar tenant (nombre → migración de referencia). */
export const SECURITY_DEFINER_RPC_CHECKS: { name: string; migrationHint: string }[] = [
  { name: "setup_user_clinic", migrationHint: "024" },
  { name: "seed_pami_cabecera_for_clinic", migrationHint: "030" },
  { name: "submit_public_booking", migrationHint: "010" },
  { name: "get_public_booking_occupancy", migrationHint: "045" },
  { name: "clinic_subscription_active", migrationHint: "047" },
  { name: "can_write_clinical", migrationHint: "047" },
  { name: "get_patient_appointment_statuses", migrationHint: "022" },
  { name: "seed_demo_patients_for_clinic", migrationHint: "019" },
  { name: "claim_clinic_jobs", migrationHint: "051" },
  { name: "complete_clinic_job", migrationHint: "051" },
  { name: "purge_old_observability_events", migrationHint: "052" },
  { name: "accept_clinic_invitations_for_user", migrationHint: "018" },
  { name: "cancel_patient_appointment", migrationHint: "026" },
  { name: "record_patient_data_consent", migrationHint: "033" },
  { name: "record_informed_consent", migrationHint: "098" },
  { name: "withdraw_patient_consent", migrationHint: "134" },
  { name: "record_clinic_legal_consent", migrationHint: "134" },
  { name: "remove_clinic_member_user", migrationHint: "035" },
  { name: "delete_own_account", migrationHint: "039" },
  { name: "update_my_doctor_profile", migrationHint: "025" },
  { name: "search_pami_vademecum", migrationHint: "042" },
  { name: "search_medication_catalog", migrationHint: "107" },
  { name: "search_pathologies", migrationHint: "005" },
  { name: "search_clinical_diagnoses", migrationHint: "112" },
  { name: "search_clinical_treatments", migrationHint: "113" },
  { name: "search_symptoms", migrationHint: "011" },
  { name: "search_pathologies_by_symptoms", migrationHint: "011" },
  { name: "claim_user_device_session", migrationHint: "109" },
  { name: "touch_user_device_session", migrationHint: "109" },
  { name: "revoke_user_device_session", migrationHint: "109" },
  { name: "assert_entitlement_clinic_access", migrationHint: "123" },
  { name: "get_clinic_entitlements", migrationHint: "121" },
  { name: "increment_feature_usage", migrationHint: "121" },
  { name: "try_consume_feature_usage", migrationHint: "121" },
  { name: "onboard_clinic_entitlement_subscription", migrationHint: "121" },
  { name: "assert_entitlement_superadmin", migrationHint: "122" },
  { name: "assign_clinic_entitlement_plan", migrationHint: "122" },
  { name: "upsert_clinic_feature_override", migrationHint: "122" },
  { name: "get_clinic_entitlement_usage", migrationHint: "124" },
  { name: "set_clinic_entitlement_status", migrationHint: "124" },
  { name: "clinic_current_entitlement_subscription_id", migrationHint: "125" },
  { name: "entitlement_metered_commercially_blocked", migrationHint: "126" },
  { name: "clear_clinic_feature_override", migrationHint: "126" },
  { name: "entitlement_subscription_is_live", migrationHint: "127" },
  { name: "set_clinic_entitlement_trial_end", migrationHint: "127" },
  { name: "expire_lapsed_clinic_entitlement_trials", migrationHint: "128" },
  // Phase 10 — public API tenant gate
  { name: "assert_public_api_clinic_access", migrationHint: "133" },
  { name: "api_list_appointments", migrationHint: "104/133" },
  { name: "api_submit_appointment", migrationHint: "104/133" },
];
